version: "3.9"

name: services-s3-gateway

services:
  s3.service:
    image: ${S3_IMAGE}
    container_name: ${S3_HOST}
    restart: ${GENERIC_RESTART}
    command:
      - "server"
      - "/data"
      - "--console-address=:${S3_CONSOLE_INTERNAL_PORT}"
    healthcheck:
      test: "bash -c 'printf \"GET / HTTP/1.1\n\n\" > /dev/tcp/127.0.0.1/9000; exit $?;'"
      interval: 10s
      retries: 60
      start_period: 20s
      timeout: 10s
    environment:
      MINIO_ROOT_USER: ${S3_USER}
      MINIO_ROOT_PASSWORD: ${S3_PASSWORD}
    ports:
      - ${S3_PORT}:9000
      - ${S3_CONSOLE_PORT}:${S3_CONSOLE_INTERNAL_PORT}
    volumes:
      - volume_s3:/data
    networks:
      - shared_network

  s3.client:
    image: ${S3_CLIENT_IMAGE}
    container_name: ${S3_CLIENT_HOST}
    depends_on:
      s3.service:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set s3_minio_server http://s3.service:9000 ${S3_CLIENT_ACCESS_KEY} ${S3_CLIENT_SECRET_KEY};
      /usr/bin/mc mb s3_minio_server/${S3_CLIENT_BUCKET_NAME} || true;
      exit 0;
      "
    networks:
      - shared_network

  s3.gateway.service:
    image: ${S3_GATEWAY_RS_IMAGE}
    container_name: ${S3_GATEWAY_RS_HOST}
    restart: ${GENERIC_RESTART}
    depends_on:
      s3.service:
        condition: service_healthy
    environment:
      S3_URL: ${S3_GATEWAY_RS_S3_URL}
      API_KEY: ${S3_GATEWAY_RS_API_KEY}
      SECRET_KEY: ${S3_GATEWAY_RS_SECRET_KEY}
      BUCKET_NAME: ${S3_GATEWAY_RS_BUCKET_NAME}
    ports:
      - ${S3_GATEWAY_RS_PORT}:7878
    networks:
      - shared_network

  ui.gateway:
    image: ${GATEWAY_IMAGE}
    container_name: ${GATEWAY_HOST}
    depends_on:
      s3.gateway.service:
        condition: service_started
      s3.service:
        condition: service_started
    ports:
      - ${GATEWAY_PORT}:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/gateway/default.conf:/etc/nginx/default.conf
      - ./nginx/api/:/etc/nginx/api_conf.d/
      - ./nginx/upstreams/:/etc/nginx/api_upstreams_conf.d/
      - ./nginx/api_json_errors.conf:/etc/nginx/api_json_errors.conf
      - ./nginx/njs/:/etc/nginx/njs/
    networks:
      - shared_network

networks:
  shared_network:
    name: ${DEFAULT_NETWORK}
     
volumes:
  volume_s3:
    name: ${S3_VOLUME}