version: "3.9"

name: services-s3-gateway

services:

  s3.gateway.service:
    image: ${S3_GATEWAY_RS_IMAGE}
    container_name: ${S3_GATEWAY_RS_HOST}
    restart: ${GENERIC_RESTART}
    environment:
      S3_URL: ${S3_GATEWAY_RS_S3_URL}
      BUCKET_NAME: ${S3_GATEWAY_RS_BUCKET_NAME}
      API_KEY: ${S3_GATEWAY_RS_API_KEY}
      SECRET_KEY: ${S3_GATEWAY_RS_SECRET_KEY}
    ports:
      - ${S3_GATEWAY_RS_PORT}:7878
    networks:
      - shared_network
  
  s3.service:
    image: ${S3_IMAGE}
    container_name: ${S3_HOST}
    restart: ${GENERIC_RESTART}
    ports:
      - ${S3_PORT}:9000
      - ${S3_CONSOLE_PORT}:9090
    command:
      - "server"
      - "/data"
      - "--console-address=:9090"
    environment:
      MINIO_ROOT_USER: ${S3_USER}
      MINIO_ROOT_PASSWORD: ${S3_PASSWORD}
    volumes:
      - volume_s3:/data
    networks:
      - shared_network

networks:
  shared_network:
    name: ${DEFAULT_NETWORK}
     
volumes:
  volume_s3:
    name: ${S3_VOLUME}